In [ ]:
import numpy as np
#retail dataset as numpy array
retail_np_array = np.array([
    [1001, "Laptop", 1, 50000, 50000],
    [1002, "Mouse", 2, 500, 1000],
    [1003, "Keyboard", 1, 1000, 1000],
    [1004, "Monitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000]
  ],  dtype=object)

# Extracting columns

In [ ]:
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
retail_np_array.shape

(5, 5)

In [ ]:
retail_np_array.size

25

In [ ]:
retail_np_array[:,0]

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [ ]:
retail_np_array[0:1]

array([[1001, 'Laptop', 1, 50000, 50000]], dtype=object)

In [ ]:
retail_np_array[0:4]

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000]], dtype=object)

In [ ]:
retail_np_array[1:4]

array([[1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000]], dtype=object)

In [ ]:
retail_np_array[1:,4]

array([1000, 1000, 14000, 2000], dtype=object)

In [ ]:
retail_np_array[:,1]

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
      dtype=object)

In [ ]:
retail_np_array[:,2]

array([1, 2, 1, 2, 1], dtype=object)

In [ ]:
retail_np_array[:,3]

array([50000, 500, 1000, 7000, 2000], dtype=object)

In [ ]:
totals=retail_np_array[:,4]

array([50000, 1000, 1000, 14000, 2000], dtype=object)

In [ ]:
retail_np_array


array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [ ]:
retail_np_array.shape[0]

(5,)

In [ ]:
retail_np_array.shape[0],retail_np_array.shape[1]

(5, 5)

In [ ]:
#totals=np.array([[100,200,300,400],[600,400,700,800]])

In [ ]:
print("Total revenue generated :",np.sum(totals))

Total revenue generated : 3500


In [ ]:

print("Total revenue generated",np.sum(totals))


Total revenue generated 3500


In [ ]:
print("Average order value :", np.mean(totals))


Average order value : 437.5


In [ ]:
print("Product with the highest total price ",[np.argmax(totals)]),



Product with the highest total price  [np.int64(7)]


(None,)

In [ ]:
print("Product with the lowest total price" ,[np.argmin (totals)]),


Product with the lowest total price [np.int64(0)]


(None,)

In [ ]:
print("Average price of products", np.mean (price))



NameError: name 'price' is not defined